spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/soknaddb
    username: soknad
    password: soknad1234
  data:
    redis:
      password: ${REDIS_PASSWORD_CACHE:pw}
      host: ${REDIS_HOST_CACHE:localhost}
      username: ${REDIS_USERNAME_CACHE:default}
      port: ${REDIS_PORT_CACHE:6379}
      ssl:
        enabled: false
      connect-timeout: 500
      timeout: 500

springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  group-configs:
    - group: 'old'
      display-name: "Old api"
      packages-to-exclude:
        - 'no.nav.sosialhjelp.soknad.v2'
    - group: 'new'
      display-name: "New api"
      packages-to-scan:
        - 'no.nav.sosialhjelp.soknad.v2'
