application:
  name: ${NAIS_APP_NAME:sosialhjelp-soknad-api}
  version: ${NAIS_APP_IMAGE:version}

srvsoknadsosialhjelp.server.username: ${SRVSOKNADSOSIALHJELP_SERVER_USERNAME:srvuser}
srvsoknadsosialhjelp.server.password: ${SRVSOKNADSOSIALHJELP_SERVER_PASSWORD:pw123}

server:
  port: ${PORT:8181}

spring:
  flyway:
    locations: classpath:postgres/migration
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:sendsoknad;sql.syntax_pgs=true
    user: sa
    password:
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:sendsoknad;sql.syntax_pgs=true
    username: sa
    password:

metrics.report.enabled: false
sensu_client_host: 127.0.0.1
sensu_client_port: 8989

environment.name: ${ENVIRONMENT_NAME:local}

mock-alt-api-host: ${MOCK_ALT_API_HOST:127.0.0.1}
mock-alt-api-wellknown-queryparam: ${MOCK_ALT_API_WELLKNOWN_QUERYPARAM:}

# rest
digisos_api_baseurl: ${DIGISOS_API_BASEURL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/fiks/}
ereg_proxy_url: ${EREG_PROXY_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/ereg/}
aareg_proxy_url: ${AAREG_PROXY_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/aareg/}
krr_proxy_url: ${KRR_PROXY_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/krr_endpoint_url/}
pdl_api_url: ${PDL_API_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/pdl_endpoint_url/}
kodeverk_proxy_url: ${KODEVERK_PROXY_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/kodeverk/}
unleash_api_url: ${UNLEASH_API_URL:https://unleash.nais.io/api}
norg_proxy_url: ${NORG_PROXY_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/norg_endpoint_url/}
fss_proxy_ping_url: ${FSS_PROXY_PING_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/fss-proxy/ping}
oppslag_api_baseurl: ${OPPSLAG_API_BASEURL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/oppslag-api/}
soknad.bostotte.url: ${SOKNAD_BOSTOTTE_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/husbanken}
svarut_url: ${SVARUT_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/svarut/}
skatteetaten_api_baseurl: ${SKATTEETATEN_API_BASEURL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/skatteetaten/}

# fiks
fiks.nokkelfil: ${FIKS_NOKKELFIL:svarut_public_test.pem}

# svarut
fiks_svarut_username: fiks_username
fiks_svarut_password: fiks_pw

integrasjonsid_fiks: id1
integrasjonpassord_fiks: pw1

# maskinporten
maskinporten_clientid: maskinporten_clientid
maskinporten_scopes: scopes
maskinporten_well_known_url: ${MASKINPORTEN_WELL_KNOWN_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/well-known/maskinporten${mock-alt-api-wellknown-queryparam}}
maskinporten_client_jwk: generateRSA

# tokenx
tokendings_url: ${TOKEN_X_WELL_KNOWN_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/well-known/tokenx${mock-alt-api-wellknown-queryparam}}
tokendings_client_id: ${TOKEN_X_CLIENT_ID:localhost:teamdigisos:sosialhjelp-dialog-api}
tokendings_private_jwk: ${TOKEN_X_PRIVATE_JWK:generateRSA}
fss_proxy_audience: ${FSS_PROXY_AUDIENCE:dummyAudience}
oppslag_api_audience: ${OPPSLAG_API_AUDIENCE:dummyAudience}
pdl_api_audience: ${PDL_API_AUDIENCE:dummyAudience}

# azuread
azure_token_endpoint: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/azuretoken/azuread}
azure_client_id: ${AZURE_APP_CLIENT_ID:localhost:teamdigisos:sosialhjelp-soknad-api}
azure_client_secret: ${AZURE_APP_CLIENT_SECRET:clientSecret}
pdl_api_scope: ${PDL_API_SCOPE:dummyScope}

# OIDC
oidc.issuer.selvbetjening.cookie_name: localhost-idtoken
oidc.issuer.selvbetjening.accepted_audience: someaudience
oidc.issuer.selvbetjening.discoveryurl: ${OIDC_ISSUER_SELVBETJENING_DISCOVERYURL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/well-known/selvbetjening${mock-alt-api-wellknown-queryparam}}
oidc.issuer.selvbetjening.proxy_url: dummy

loginservice.url: ${LOGINSERVICE_URL:http://localhost:3009/sosialhjelp/mock-alt/login}

soknad.vedlegg.virusscan.enabled: false
soknad.ettersending.antalldager: 180

# redis
redis_host: ${REDIS_HOST:localhost}
redis_port: 6379
redis_password: ${REDIS_PASSWORD:pw}

# Feature toggles
unleash_instance_id: ${UNLEASH_INSTANCE_ID:labs-gcp}
scheduler.disable: ${SCHEDULER_DISABLE:false}
digisosapi.sending.enable: ${IS_SENDING_TIL_DIGISOS_API_ENABLED:true}
digisosapi.sending.alltidTilTestkommune.enable: ${IS_ALLTID_SEND_TIL_NAV_TESTKOMMUNE:false}
digisosapi.henting.alltidTestkommune.enable: ${IS_ALLTID_HENT_KOMMUNEINFO_FRA_NAV_TESTKOMMUNE:false}
sendsoknad.batch.enabled: true
feature.fiks.kryptering.enabled: true

#Nedetid
nedetid.start: ${NEDETID_START:}
nedetid.slutt: ${NEDETID_SLUTT:}
