spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true
    default-schema: soknad
  docker:
    compose:
      enabled: true
      file: compose/docker-compose-local.yml