spring:
  docker:
    compose:
      file: "compose/docker-compose-local.yml"
      lifecycle-management: start-only
      enabled: true
      # Fjern denne dersom du kun Ã¸nsker redis/postgres, ikke mock-alt & -api
      profiles:
        active: "full"
      # Dersom database skal nullstilles hver gang applikasjonen restarter:
      #lifecycle-management: start-and-stop
      #stop:
      #  command=down
