server:
  port: ${PORT:8181}

spring:
  flyway:
    enabled: false
  #    baseline-on-migrate: true
  #    url: jdbc:hsqldb:mem:sendsoknad;sql.syntax_ora=true
  #    user: sa
  #    password:
  #    driver-class-name: org.hsqldb.jdbcDriver
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:sendsoknad;sql.syntax_ora=true
    username: sa
    password:

mock-alt-api-host: ${MOCK_ALT_API_HOST:127.0.0.1}
mock-alt-api-wellknown-queryparam: ${MOCK_ALT_API_WELLKNOWN_QUERYPARAM:}

# rest
digisos_api_baseurl: ${DIGISOS_API_BASEURL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/fiks/}
ereg_url: ${EREG_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/ereg}
aareg_url: ${AAREG_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/aareg/}
krr_url: ${KRR_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/krr/}
pdl_api_url: ${PDL_API_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/pdl_endpoint_url}
kodeverk_url: ${KODEVERK_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/kodeverk}
unleash_api_url: ${UNLEASH_API_URL:https://unleash.nais.io/api}
norg_url: ${NORG_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/norg_endpoint_url}
oppslag_api_baseurl: ${OPPSLAG_API_BASEURL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/oppslag-api/}
utbetaldata_api_baseurl: ${UTBETALDATA_API_BASEURL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api}
kontoregister_api_baseurl: ${KONTOREGISTER_API_BASEURL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api}
soknad.bostotte.url: ${SOKNAD_BOSTOTTE_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/husbanken}
svarut_url: ${SVARUT_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/svarut/}
skatteetaten_api_baseurl: ${SKATTEETATEN_API_BASEURL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/skatteetaten/}
clamav_url: virusscan_not_enabled

# fiks
fiks.nokkelfil: ${FIKS_NOKKELFIL:svarut_public_test.pem}

# svarut
fiks_svarut_username: fiks_username
fiks_svarut_password: fiks_pw

integrasjonsid_fiks: id1
integrasjonpassord_fiks: pw1

# maskinporten
maskinporten_clientid: maskinporten_clientid
maskinporten_scopes: scopes
maskinporten_well_known_url: ${MASKINPORTEN_WELL_KNOWN_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/well-known/maskinporten${mock-alt-api-wellknown-queryparam}}
maskinporten_client_jwk: generateRSA

# tokenx
tokendings_url: ${TOKEN_X_WELL_KNOWN_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/well-known/tokenx${mock-alt-api-wellknown-queryparam}}
tokendings_client_id: ${TOKEN_X_CLIENT_ID:dummyAudience}
tokendings_private_jwk: ${TOKEN_X_PRIVATE_JWK:generateRSA}
oppslag_api_audience: ${OPPSLAG_API_AUDIENCE:dummyAudience}
kontoregister_api_audience: ${KONTOREGISTER_API_AUDIENCE:dummyAudience}
pdl_api_audience: ${PDL_API_AUDIENCE:dummyAudience}
utbetaldata_audience: ${UTBETALDATA_AUDIENCE:dummyAudience}
krr_audience: ${KRR_AUDIENCE:dummyAudience}
aareg_audience: ${AAREG_AUDIENCE:dummyAudience}

# azuread
azure_token_endpoint: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/azuretoken/azuread}
azure_client_id: ${AZURE_APP_CLIENT_ID:localhost:teamdigisos:sosialhjelp-soknad-api}
azure_client_secret: ${AZURE_APP_CLIENT_SECRET:clientSecret}
pdl_api_scope: ${PDL_API_SCOPE:dummyScope}
krr_scope: ${KRR_SCOPE:dummyScope}

no.nav.security.jwt.issuer:
  azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/well-known/azuread${mock-alt-api-wellknown-queryparam}}
    accepted_audience: someaudience
  selvbetjening:
    discoveryurl: ${OIDC_ISSUER_SELVBETJENING_DISCOVERYURL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/well-known/selvbetjening${mock-alt-api-wellknown-queryparam}}
    accepted_audience: someaudience
    cookie_name: localhost-idtoken
    proxyurl:
  tokenx:
    discoveryurl: ${TOKEN_X_WELL_KNOWN_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/well-known/tokenx${mock-alt-api-wellknown-queryparam}}
    accepted_audience: ${TOKEN_X_CLIENT_ID:dummyAudience}

loginservice.url: ${LOGINSERVICE_URL:http://localhost:3008/sosialhjelp/mock-alt/login}

virusscan_enabled: false

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}

# redis
redis_host: ${REDIS_HOST:localhost}
redis_port: 6379
redis_password: ${REDIS_PASSWORD:pw}

# Feature toggles
unleash_instance_id: ${UNLEASH_INSTANCE_ID:mock}
scheduler.disable: ${SCHEDULER_DISABLE:false}
sendsoknad.batch.enabled: true
feature.fiks.kryptering.enabled: false

#Nedetid
nedetid.start: ${NEDETID_START:}
nedetid.slutt: ${NEDETID_SLUTT:}
