[versions]
kotlin = "2.3.0"
spring-boot = "4.0.1"
coroutines = "1.10.2"
filformat = "1.2026.01.19-15.17-55bb3d1bca81"
sosialhjelp_common = "1.20250120.1009-d88048d"
fiks_kryptering = "2.1.0"
springdoc = "3.0.1"
flyway = "11.20.2"
postgres = "42.7.9"
lettuce = "7.2.1.RELEASE"
token_validation = "5.0.25"
java_jwt = "4.5.0"
prometheus = "0.16.0"
micrometer = "1.16.2"
jackson = "3.0.3"
logback = "1.5.24"
logstash = "9.0"
pdfbox = "3.0.6"
jakarta_servlet = "6.1.0"
unleash_client = "12.0.1"
tika = "3.2.3"
commons_text = "1.15.0"
ktlint = "1.2.1"
mockk = "1.14.7"
versions = "0.53.0"
resilience4j = "2.3.0"
spotless = "8.1.0"
opentelemetry = "1.58.0"
opentelemetry-logback = "2.23.0-alpha"
testcontainers = "1.21.4"
ninja-springmockk = "5.0.1"
jsonassert = "1.5.3"

[libraries]
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "spring-boot" }
spring-boot-starter-aspectj = { module = "org.springframework.boot:spring-boot-starter-aspectj", version.ref = "spring-boot" }
spring-boot-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache", version.ref = "spring-boot" }
spring-boot-starter-data-jdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc", version.ref = "spring-boot" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis", version.ref = "spring-boot" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "spring-boot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway", version.ref = "spring-boot" }
spring-boot-starter-webclient = { module = "org.springframework.boot:spring-boot-starter-webclient", version.ref = "spring-boot" }

spring-boot-starter-cache-test = { module = "org.springframework.boot:spring-boot-starter-cache-test", version.ref = "spring-boot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
spring-boot-starter-data-jdbc-test = { module = "org.springframework.boot:spring-boot-starter-data-jdbc-test", version.ref = "spring-boot" }
spring-boot-starter-webflux-test = { module = "org.springframework.boot:spring-boot-starter-webflux-test", version.ref = "spring-boot" }
spring-boot-starter-data-redis-test = { module = "org.springframework.boot:spring-boot-starter-data-redis-test", version.ref = "spring-boot" }

resilience4j-kotlin = { module = "io.github.resilience4j:resilience4j-kotlin", version.ref = "resilience4j" }
resilience4j-retry = { module = "io.github.resilience4j:resilience4j-retry", version.ref = "resilience4j" }
resilience4j-spring-boot3 = { module = "io.github.resilience4j:resilience4j-spring-boot3", version.ref = "resilience4j" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-slf4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "coroutines" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

soknadsosialhjelp-filformat = { module = "no.nav.sbl.dialogarena:soknadsosialhjelp-filformat", version.ref = "filformat" }

sosialhjelp-common-api = { module = "no.nav.sosialhjelp:sosialhjelp-common-api", version.ref = "sosialhjelp_common" }
sosialhjelp-common-selftest = { module = "no.nav.sosialhjelp:sosialhjelp-common-selftest", version.ref = "sosialhjelp_common" }

kryptering = { module = "no.ks.fiks:kryptering", version.ref = "fiks_kryptering" }

springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
springdoc-openapi-starter-common = { module = "org.springdoc:springdoc-openapi-starter-common", version.ref = "springdoc" }

flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-database-postgres = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }

lettuce-core = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }
token-validation-spring = { module = "no.nav.security:token-validation-spring", version.ref = "token_validation" }
java-jwt = { module = "com.auth0:java-jwt", version.ref = "java_jwt" }
simpleclient = { module = "io.prometheus:simpleclient", version.ref = "prometheus" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer" }

jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin", version.ref = "jackson" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash" }
jakarta-servlet-api = { module = "jakarta.servlet:jakarta.servlet-api", version.ref = "jakarta_servlet" }
unleash-client-java = { module = "io.getunleash:unleash-client-java", version.ref = "unleash_client" }
tika-core = { module = "org.apache.tika:tika-core", version.ref = "tika" }
# vises som unused, men er n√∏dvendig (se build.gradle)
tika-parsers-standard-package = { module = "org.apache.tika:tika-parsers-standard-package", version.ref = "tika" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons_text" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }
preflight = { module = "org.apache.pdfbox:preflight", version.ref = "pdfbox" }
pdfbox-io = { module = "org.apache.pdfbox:pdfbox-io", version.ref = "pdfbox" }
opentelemetry-bom = { module = "io.opentelemetry:opentelemetry-bom", version.ref = "opentelemetry" }
opentelemetry-api = { module = "io.opentelemetry:opentelemetry-api" }
opentelemetry-instrumentation-logback = { module = "io.opentelemetry.instrumentation:opentelemetry-logback-mdc-1.0", version.ref = "opentelemetry-logback" }

token-validation-spring-test = { module = "no.nav.security:token-validation-spring-test", version.ref = "token_validation" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-jvm = { module = "io.mockk:mockk-jvm", version.ref = "mockk" }

testcontainers-postgres = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }

ninja-springmockk = { module = "com.ninja-squad:springmockk", version.ref = "ninja-springmockk" }
jsonassert = { module = "org.skyscreamer:jsonassert", version.ref = "jsonassert" }

[bundles]
spring-boot = [
    "spring-boot-starter-actuator",
    "spring-boot-starter-aspectj",
    "spring-boot-starter-cache",
    "spring-boot-starter-data-jdbc",
    "spring-boot-starter-data-redis",
    "spring-boot-starter-validation",
    "spring-boot-starter-web",
    "spring-boot-starter-flyway",
    "spring-boot-starter-webclient",
]

spring-boot-test = [
    "spring-boot-starter-test",
    "spring-boot-starter-data-jdbc-test",
    "spring-boot-starter-webflux-test",
    "spring-boot-starter-cache-test",
    "spring-boot-starter-data-redis-test",
]

resilience4j = [
    "resilience4j-kotlin",
    "resilience4j-retry",
    "resilience4j-spring-boot3"
]

coroutines = [
    "kotlinx-coroutines-slf4j",
    "kotlinx-coroutines-reactor",
    "kotlinx-coroutines-core",
    "kotlinx-coroutines-test",
]

pdfbox = [
    "pdfbox",
    "pdfbox-io",
    "preflight",
]

sosialhjelp-common = [
    "sosialhjelp-common-selftest",
    "sosialhjelp-common-api",
]


[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

