[versions]
kotlin = "1.9.23"
spring-boot = "3.2.4"
coroutines = "1.8.0"
filformat = "1.2023.07.11-15.37-bb76af3d1843"
sosialhjelp_common = "1.20231205.0930-5ce172f"
fiks_svar_ut = "4.1.0"
fiks_kryptering = "2.0.3"
springdoc = "2.5.0"
flyway_plugin = "10.11.0"
flyway = "10.11.0"
ojdbc_10 = "19.22.0.0"
hsqldb = "2.7.2"
lettuce = "6.3.2.RELEASE"
token_validation = "4.1.4"
java_jwt = "4.4.0"
prometheus = "0.16.0"
micrometer = "1.12.5"
jackson = "2.17.0"
logback = "1.5.4"
logstash = "7.4"
pdfbox = "3.0.2"
jakarta_servlet = "6.0.0"
unleash_client = "9.2.0"
tika = "2.9.2"
tika_parsers = "2.9.2"
commons_text = "1.11.0"
ktlint = "0.47.1"
mockk = "1.13.10"
versions = "0.51.0"
vault_jdbc = "1.3.10"
resilience4j = "2.2.0"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "spring-boot" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "spring-boot" }
spring-boot-starter-data-jdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc", version.ref = "spring-boot" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis", version.ref = "spring-boot" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "spring-boot" }
spring-boot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aop", version.ref = "spring-boot" }
spring-boot-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache", version.ref = "spring-boot" }

resilience4j-kotlin = { module = "io.github.resilience4j:resilience4j-kotlin", version.ref = "resilience4j" }
resilience4j-retry = { module = "io.github.resilience4j:resilience4j-retry", version.ref = "resilience4j" }
resilience4j-spring-boot3 = { module = "io.github.resilience4j:resilience4j-spring-boot3", version.ref = "resilience4j" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-slf4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "coroutines" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "coroutines" }

soknadsosialhjelp-filformat = { module = "no.nav.sbl.dialogarena:soknadsosialhjelp-filformat", version.ref = "filformat" }

sosialhjelp-common-api = { module = "no.nav.sosialhjelp:sosialhjelp-common-api", version.ref = "sosialhjelp_common" }
sosialhjelp-common-selftest = { module = "no.nav.sosialhjelp:sosialhjelp-common-selftest", version.ref = "sosialhjelp_common" }
sosialhjelp-common-kotlin-utils = { module = "no.nav.sosialhjelp:sosialhjelp-common-kotlin-utils", version.ref = "sosialhjelp_common" }

vault-jdbc = { module = "no.nav:vault-jdbc", version.ref = "vault_jdbc" }

svarut-rest-klient = { module = "no.ks.fiks.svarut:svarut-rest-klient", version.ref = "fiks_svar_ut" }
kryptering = { module = "no.ks.fiks:kryptering", version.ref = "fiks_kryptering" }

springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
springdoc-openapi-starter-common = { module = "org.springdoc:springdoc-openapi-starter-common", version.ref = "springdoc" }

flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
lettuce-core = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }
token-validation-spring = { module = "no.nav.security:token-validation-spring", version.ref = "token_validation" }
java-jwt = { module = "com.auth0:java-jwt", version.ref = "java_jwt" }
simpleclient = { module = "io.prometheus:simpleclient", version.ref = "prometheus" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash" }
jakarta-servlet-api = { module = "jakarta.servlet:jakarta.servlet-api", version.ref = "jakarta_servlet" }
unleash-client-java = { module = "io.getunleash:unleash-client-java", version.ref = "unleash_client" }
tika-core = { module = "org.apache.tika:tika-core", version.ref = "tika" }
tika-parsers-standard-package = { module = "org.apache.tika:tika-parsers-standard-package", version.ref = "tika_parsers" }
ojdbc10 = { module = "com.oracle.database.jdbc:ojdbc10", version.ref = "ojdbc_10" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons_text" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }
preflight = { module = "org.apache.pdfbox:preflight", version.ref = "pdfbox" }
pdfbox-io = { module = "org.apache.pdfbox:pdfbox-io", version.ref = "pdfbox" }

spring-boot-docker-compose = { module = "org.springframework.boot:spring-boot-docker-compose", version.ref = "spring-boot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
token-validation-spring-test = { module = "no.nav.security:token-validation-spring-test", version.ref = "token_validation" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-jvm = { module = "io.mockk:mockk-jvm", version.ref = "mockk" }

[bundles]
spring-boot = [
    "spring-boot-starter-actuator",
    "spring-boot-starter-aop",
    "spring-boot-starter-cache",
    "spring-boot-starter-data-jdbc",
    "spring-boot-starter-data-redis",
    "spring-boot-starter-test",
    "spring-boot-starter-validation",
    "spring-boot-starter-web",
    "spring-boot-starter-webflux",
]

resilience4j = [
    "resilience4j-kotlin",
    "resilience4j-retry",
    "resilience4j-spring-boot3"
]

coroutines = [
    "kotlinx-coroutines-slf4j",
    "kotlinx-coroutines-reactor",
    "kotlinx-coroutines-core",
]

springdoc = [
    "springdoc-openapi-starter-common",
    "springdoc-openapi-starter-webmvc-ui",
]

pdfbox = [
    "pdfbox",
    "pdfbox-io",
    "preflight",
]

sosialhjelp-common = [
    "sosialhjelp-common-selftest",
    "sosialhjelp-common-api",
    "sosialhjelp-common-kotlin-utils",
]


[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.1.0" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway_plugin" }
