name: Build image
env:
  ARTIFACT_NAME: app.jar
on:
  push:
    branches:
      - '**' # Build all branches
    tags-ignore:
      - '**' # Don't build any tags
  workflow_dispatch:

# FIXME: Legg til docker layer caching, f.eks. https://github.com/marketplace/actions/build-docker-images-using-cache
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
#      DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
      ORG_GRADLE_PROJECT_githubUser: x-access-token
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Run lint
        run: ./gradlew ktlintCheck
      - name: Compile and run tests
        run: ./gradlew build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ///home/runner/work/sosialhjelp-soknad-api/sosialhjelp-soknad-api/build/libs/app.jar
          if-no-files-found: error
          retention-days: 1

  handle_image:
    name: Build, push, tag and release image
    if: github.actor != 'dependabot[bot]'
    needs: build
    uses: navikt/sosialhjelp-workflows/.github/workflows/build_image.yml@main
    with:
      artifact_name: ${{ env.ARTIFACT_NAME }}
      image_name: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
