name: Build kotlin and docker image
on:
  push:
    branches:
      - '**' # Build all branches
    tags-ignore:
      - '**' # Don't build any tags
  workflow_dispatch:

# FIXME: Legg til docker layer caching, f.eks. https://github.com/marketplace/actions/build-docker-images-using-cache
jobs:
  build:
    name: Build with gradle
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    env:
      ORG_GRADLE_PROJECT_githubUser: x-access-token
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Build kotlin, and run tests/lint
        uses: navikt/sosialhjelp-ci/actions/build-kotlin@master

      - name: Create and release tag
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-and-release-tag@master

      - name: Build and push Docker Image
        uses: navikt/sosialhjelp-ci/actions/build-and-push-docker-image@master
        with:
          image-name: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-version: ${{ steps.artifact-version.outputs.artifact-version }}

      - name: Notify channel if Dependabot PR
        uses: navikt/sosialhjelp-ci/actions/post-to-slack-action
