name: Build and push docker image
on:
  push:
    branches:
      - '**' # Build all branches
    tags-ignore:
      - '**' # Don't build any tags
  workflow_dispatch:

# FIXME: Legg til docker layer caching, f.eks. https://github.com/marketplace/actions/build-docker-images-using-cache
jobs:
  build:
    name: Build with gradle
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_githubUser: x-access-token
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Run lint
        run: ./gradlew ktlintCheck
      - name: Compile and run tests
        run: ./gradlew build
      - name: Upload jar (artifact)
        uses: actions/upload-artifact@v3
        with:
          name: app.jar
          path: ///home/runner/work/sosialhjelp-soknad-api/sosialhjelp-soknad-api/build/libs/app.jar
          if-no-files-found: error
          retention-days: 1

  image:
    name: Build, push, tag and release docker image
    if: github.actor != 'dependabot[bot]'
    needs: build # må vente på upload av jar-fil (artifact) før denne kjører
    uses: navikt/sosialhjelp-workflows/.github/workflows/build_image_java.yml@main
    with:
      image_name: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
