name: Build and push docker image
on:
  push:
    branches:
      - '**' # Build all branches
    tags-ignore:
      - '**' # Don't build any tags
  workflow_dispatch:

env:
  IMAGE-NAME: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
# FIXME: Legg til docker layer caching, f.eks. https://github.com/marketplace/actions/build-docker-images-using-cache
jobs:
  build:
    name: Build with gradle
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    env:
      ORG_GRADLE_PROJECT_githubUser: x-access-token
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Build kotlin, and run tests/lint
        uses: navikt/sosialhjelp-ci/.github/actions/build-kotlin@modularize_steps

      - name: Create and release tag
        uses: navikt/sosialhjelp-ci/.github/actions/create-and-release-tag@modularize_steps
        with:
          image-name: ${{ env.IMAGE-NAME }}
#          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: navikt/sosialhjelp-ci/.github/actions/build-and-push-docker-image@modularize_steps
        with:
          image-name: ${{ env.IMAGE-NAME }}
#          github-token: ${{ secrets.GITHUB_TOKEN }}