name: Code analysis and dependency submission

on:
  pull_request:
  workflow_dispatch:
  schedule: ## KjÃ¸rer kl. 05:00 mandag -> fredag
    - cron: '0 5 * * 1-5'

jobs:
  analyze_code:
    name: Analyze Code
    uses: navikt/sosialhjelp-workflows/.github/workflows/codeql_java.yml@main

  dependency_submission:
    name: Dependency Submission Gradle
    uses: navikt/sosialhjelp-workflows/.github/workflows/dep_sub_gradle.yml@main
