name: Code analysis and dependency submission

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1-5'

jobs:
  analyze_code:
    name: Analyze Code
    uses: navikt/sosialhjelp-workflows/.github/workflows/codeql.yml@main

  dependency_submission:
    name: Dependency Submission Gradle
    uses: navikt/sosialhjelp-workflows/.github/workflows/dependency_submission.yml@main
