name: 'Remove old packages'
on:
  schedule: ## Kjører kl. 05:00 mandag -> fredag (schedule kjører bare for Default branch)
    - cron: '0 5 * * 1'

jobs:
  remove-packages:
    name: 'Remove old packages'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'sosialhjelp-soknad-api/sosialhjelp-soknad-api'
          package-type: 'container'
          min-versions-to-keep: 20
