name: "Post Dependabot PR notifications to Slack"

on:
  pull_request:

jobs:
  event-info:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk github.event
        run: echo "${{ github.event }}"
