name: Deploy til dev
on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Hvilken config skal deployes?'
        required: true
        default: 'dev-fss'
        type: choice
        options:
          - 'mock'
          - 'dev-fss'

jobs:
  deploy:
    name: Deploy to dev - ${{ github.event.inputs.config }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
      ORG_GRADLE_PROJECT_githubUser: x-access-token
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Build kotlin, and run tests/lint
        uses: navikt/sosialhjelp-ci/actions/build-kotlin@master
        with:
          task-type: 'assemble'

      - name: Create and release tag
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-and-release-tag@master
        with:
          prefix: ${{ github.ref_name }}_

      - name: Build and push Docker Image
        uses: navikt/sosialhjelp-ci/actions/build-and-push-docker-image@master
        with:
          image-name: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-version: ${{ steps.artifact-version.outputs.artifact-version }}

      - name: Utled cluster fra valgt config
        run: |
          if [[ ${{ github.event.inputs.config }} = 'dev-fss' ]]; then
            echo "CLUSTER_NAME=dev-fss" >> $GITHUB_ENV          
          else
            echo "CLUSTER_NAME=dev-gcp" >> $GITHUB_ENV
          fi
          echo "Deployer til ${{ env.CLUSTER_NAME }}"

      - name: Deploy til dev - ${{ github.event.inputs.config }}
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/dev/${{ github.event.inputs.config }}.yaml
          CLUSTER: ${{ env.CLUSTER_NAME }}
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ env.DOCKER_TAG }}
