name: Deploy Dev
on:
  repository_dispatch:
    types: [deploy_miljo_tag]

jobs:
  deploy:
    name: Deploy to dev-sbs
    runs-on: ubuntu-latest
    if: github.event.action == 'deploy_miljo_tag'
    container: navikt/deployment-cli:0.4.0
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to dev - test 1 github.event.client_payload.MILJO 2 github.event.client_payload.TAG 3 github.event.client_payload
        run: |
          MILJO=$(jq -r '.client_payload.MILJO' $GITHUB_EVENT_PATH)
          TAG=$(jq -r '.client_payload.TAG' $GITHUB_EVENT_PATH)

          git checkout ${TAG}

          deployment-cli deploy create --cluster=dev-sbs --repository=${GITHUB_REPOSITORY} --team=teamdigisos -r=web/nais.yaml --var version=${TAG} --vars=web/nais/dev/${MILJO}.json --await=900
        env:
          DEPLOYMENT_USERNAME: ${{ secrets.DEPLOYMENT_USERNAME }}
          DEPLOYMENT_PASSWORD: ${{ secrets.DEPLOYMENT_PASSWORD }}