name: Deploy GCP
on:
  repository_dispatch:
    types: [deploy_dev_gcp]

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    if: github.event.action == 'deploy_dev_gcp'
    container: navikt/deployment:v1
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to dev
        run: |
          MILJO=$(jq -r '.client_payload.MILJO' $GITHUB_EVENT_PATH)
          TAG=$(jq -r '.client_payload.TAG' $GITHUB_EVENT_PATH)

          git checkout ${TAG}

          deployment-cli deploy create --cluster=${MILJO} --repository=${GITHUB_REPOSITORY} --team=digisos -r=web/nais.yaml --var version=${TAG} --vars=web/nais/dev/${MILJO}.json
        env:
          DEPLOYMENT_USERNAME: ${{ secrets.DEPLOYMENT_USERNAME }}
          DEPLOYMENT_PASSWORD: ${{ secrets.DEPLOYMENT_PASSWORD }}
