name: NEW - Deploy to Production
run-name: Deploy '${{ github.ref_name }}' to '${{ github.event.inputs.config }}' - build image = ${{ inputs.build-image }}
on:
  workflow_run:
    workflows: [ 'Build Kotlin, Run Lint and Test' ]    # Venter på at bygg på master har kjørt uten feil
    branches: [ master ]
    types:
      - completed

jobs:
  deploy-to-prod:
    name: 'Deploy Prod'
    permissions:
      packages: write
      contents: write
    uses: navikt/sosialhjelp-ci/.github/workflows/deploy_app.yml@master
    with:
      cluster-name: 'prod-fss'
      build-image: 'true'
      resource-folder: 'prod'
    secrets: inherit