name: Deploy til prod
on:
  workflow_run:
    workflows: ['Build Kotlin, Run Lint and Test']    # Venter på at bygg på master har kjørt uten feil
    branches: [master]
    types:
      - completed
  repository_dispatch:
    types: [deploy_prod_tag]

jobs:
  build-for-deploy:
    name: 'Build for Deploy to Production'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    env:
      ORG_GRADLE_PROJECT_githubUser: x-access-token
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      docker-image-tag: ${{ steps.build-and-release.outputs.image-tag }}
    steps:
      - name: 'Build and Tag for Deploy'
        id: build-and-release
        uses: navikt/sosialhjelp-soknad-api/.github/actions/build-for-deploy@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-fss:
    name: 'Deploy to Prod-fss'
    needs: build-for-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: deploy til prod-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/prod/prod-fss.yaml
          CLUSTER: prod-fss
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ needs.build-for-deploy.outputs.docker-image-tag }}
