name: Deploy qO
on: workflow_dispatch

jobs:
  deploy:
    name: Deploy to qO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: Sett env variabler
        run: |
          PROJECT_NAME=$(echo ${{ github.repository }} | cut -d/ -f2)
          echo "IMAGE=docker.pkg.github.com/${{ github.repository }}/$PROJECT_NAME:${{ steps.get-latest-tag.outputs.tag }}" >> $GITHUB_ENV

      - name: Deploy til q0
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: web/nais.yaml
          CLUSTER: dev-sbs
          VARS: web/nais/dev/q0.json
          REF: ${{ steps.get-latest-tag.outputs.tag }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ env.IMAGE }}