name: Deploy to Production
on:
  workflow_run:
    workflows: [ 'Build Kotlin, Run Lint and Test' ]    # Venter på at bygg på master har kjørt uten feil
    branches: [ master ]
    types:
      - completed

jobs:
  deploy-to-prod:
    name: 'Deploy to prod-fss'
    permissions:
      packages: write
      contents: write
    uses: navikt/sosialhjelp-ci/.github/workflows/deploy_app.yml@v2
    with:
      cluster-name: 'prod-fss'
      resource-folder: 'prod'
      resource-name: 'prod-fss'
      build-always: true
    secrets: inherit