name: Deploy GCP
on:
  repository_dispatch:
    types: [deploy_dev_gcp]

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    if: github.event.action == 'deploy_dev_gcp'
    container: navikt/deployment:v1
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to dev
        run: |
          git checkout ${TAG}
          echo "DEBUG:"
          echo "${GITHUB_REPOSITORY}"
          echo "...done"
          /app/deploy \
              --actions \
              --cluster="${MILJO}" \
              --apikey="${APIKEY}" \
              --resource="web/nais.yaml" \
              --team=digisos \
              --owner=navikt \
              --repository="${GITHUB_REPOSITORY}" \
              --var version=${TAG} \
              --vars="web/nais/dev/${MILJO}.json" \
              --wait
#          /app/deploy --cluster=${MILJO} --repository=${GITHUB_REPOSITORY} --team=digisos --resource=web/nais.yaml --var version=${TAG} --vars=web/nais/dev/${MILJO}.json
        env:
          MILJO: ${{ github.event.client_payload.MILJO }}
          TAG: ${{ github.event.client_payload.TAG }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          PRINT_PAYLOAD: true
          DEPLOYMENT_USERNAME: ${{ secrets.DEPLOYMENT_USERNAME }}
          DEPLOYMENT_PASSWORD: ${{ secrets.DEPLOYMENT_PASSWORD }}
