name: Deploy to Development
run-name: Deploy of ${{ github.ref_name }} to ${{ github.event.inputs.config }}
on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Hvilken config skal deployes?'
        required: true
        default: 'dev-fss'
        type: choice
        options:
          - 'mock'
          - 'dev-fss'

jobs:
  build-for-deploy:
    name: Build for Deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    env:
      ORG_GRADLE_PROJECT_githubUser: x-access-token
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      docker-image-tag: ${{ steps.build-and-release.outputs.image-tag }}
    steps:
      - name: Build and Tag for Deploy
        id: build-and-release
        uses: navikt/sosialhjelp-soknad-api/.github/actions/build-for-deploy@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dev-build: ${{ github.ref_name }}

  deploy-to-dev:
    name: Deploying ${{ github.ref_name }} to ${{ github.event.inputs.config }}
    needs: build-for-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Utled cluster fra valgt config
        run: |
          if [[ ${{ github.event.inputs.config }} = 'dev-fss' ]]; then
            echo "CLUSTER_NAME=dev-fss" >> $GITHUB_ENV          
          else
            echo "CLUSTER_NAME=dev-gcp" >> $GITHUB_ENV
          fi
          echo "Deployer til ${{ env.CLUSTER_NAME }}"

      - name: Deploy til dev - ${{ github.event.inputs.config }}
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/dev/${{ github.event.inputs.config }}.yaml
          CLUSTER: ${{ env.CLUSTER_NAME }}
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ needs.build-for-deploy.outputs.docker-image-tag }}
