name: Deploy to Production
on:
  workflow_run:
    workflows: [ 'Build Kotlin, Run Lint and Test' ]    # Venter på at bygg på master har kjørt uten feil
    branches: [ master ]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-to-prod:
    name: 'Deploy to prod-fss'
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      id-token: write
      contents: write
    uses: navikt/sosialhjelp-ci/.github/workflows/deploy_app.yml@v3
    with:
      cluster-name: 'prod-fss'
      resource-folder: 'prod'
      resource-name: 'prod-fss'
      build-always: true
    secrets: inherit
