name: Deploy GCP
on:
  repository_dispatch:
    types: [deploy_dev_gcp]

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    if: github.event.action == 'deploy_dev_gcp'
    container: navikt/deployment:v1
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to dev
        run: |
          git checkout ${TAG}
          yq w web/nais/dev/${MILJO}.json version "${TAG}" > gcp.yaml
          /app/deploy \
              --actions \
              --apikey="$NAIS_DEPLOY_APIKEY" \
              --cluster="${MILJO}" \
              --repository="$CIRCLE_PROJECT_REPONAME" \
              --resource="web/nais.yaml" \
              --vars="gcp.yaml" \
              --wait=true
#          /app/deploy --cluster=${MILJO} --repository=${GITHUB_REPOSITORY} --team=digisos --resource=web/nais.yaml --var version=${TAG} --vars=web/nais/dev/${MILJO}.json
        env:
          MILJO: ${{ github.event.client_payload.MILJO }}
          TAG: ${{ github.event.client_payload.TAG }}
          DEPLOYMENT_USERNAME: ${{ secrets.DEPLOYMENT_USERNAME }}
          DEPLOYMENT_PASSWORD: ${{ secrets.DEPLOYMENT_PASSWORD }}
