name: 'Deploy to stable environments v2'
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ 'Build Kotlin, Run Lint and Test' ]    # Venter på at bygg på master har kjørt uten feil
    branches: [ main ]
    paths-ignore:
      - '*.md' # Ignorerer endringer i markdown-filer
    types:
      - completed

jobs:
  deploy-to-stable:
    name: 'Deploy to Prod and Prod-test'
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      id-token: write
      contents: write
    uses: navikt/sosialhjelp-ci/.github/workflows/deploy_to_stable.yml@v17
    with:
      prod-resource: 'prod-gcp.yaml'
      test-resource: 'preprod.yaml'
    secrets: inherit
