name: Deploy til prod
on:
  workflow_run:
    workflows: ["Build Kotlin"]    # Hvis 'build' g√•r bra, skal det deployes
    branches: [master]
    types:
      - completed
  repository_dispatch:
    types: [deploy_prod_tag]

jobs:
  deploy-fss:
    name: Deploy to prod-fss
    if: ${{ github.event_name == 'repository_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
      ORG_GRADLE_PROJECT_githubUser: x-access-token
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Build kotlin, and run tests/lint
        uses: navikt/sosialhjelp-ci/actions/build-kotlin@master
        with:
          task-type: 'assemble'

      - name: Create and release tag
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-and-release-tag@master

      - name: Build and push Docker Image
        uses: navikt/sosialhjelp-ci/actions/build-and-push-docker-image@master
        with:
          image-name: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-version: ${{ steps.artifact-version.outputs.artifact-version }}

      - name: deploy til prod-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/prod/prod-fss.yaml
          CLUSTER: prod-fss
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ env.DOCKER_TAG }}
