name: Deploy to Production
on:
  workflow_run:
    workflows: ['Build Kotlin, Run Lint and Test']    # Venter på at bygg på master har kjørt uten feil
    branches: [master]
    types:
      - completed
  repository_dispatch:
    types: [deploy_prod_tag]

jobs:
  build-for-deploy:
    name: 'Build for Deploy to Production'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
      ORG_GRADLE_PROJECT_githubUser: x-access-token
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      docker-image-tag: ${{ steps.current-image-tag.outputs.image-tag }}
    steps:
      - name: 'Create and release tag'
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-and-release-tag@master

      - name: 'Assemble code'
        uses: navikt/sosialhjelp-ci/actions/build-kotlin@master
        with:
          task-type: 'assemble'

      - name: 'Build and push Docker Image'
        uses: navikt/sosialhjelp-ci/actions/build-and-push-docker-image@master
        with:
          image-name: ${{ env.DOCKER_IMAGE }}
          github-token: ${{ inputs.github-token }}
          artifact-version: ${{ steps.artifact-version.outputs.artifact-version }}

      - id: current-image-tag
        run: |
          echo "image-tag=${{ env.DOCKER_IMAGE }}:${{ steps.artifact-version.outputs.artifact-version }}" >> $GITHUB_OUTPUT

  deploy-fss:
    name: 'Deploy to prod-fss'
    needs: build-for-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: deploy til prod-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/prod/prod-fss.yaml
          CLUSTER: prod-fss
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ needs.build-for-deploy.outputs.docker-image-tag }}
