name: 'NEW - Deploy to Development'
run-name: Deploy '${{ github.ref_name }}' to '${{ github.event.inputs.config }}'
on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Deploye til mock(=dev-gcp) eller dev-fss?'
        required: true
        default: 'dev-fss'
        type: choice
        options:
          - 'dev-gcp'
          - 'dev-fss'

jobs:
  deploy-to-dev:
    name: 'Deploy to dev'
    permissions:
      packages: write
      contents: write
    uses: navikt/sosialhjelp-ci/.github/workflows/new_deploy_app.yml@v2
    with:
      cluster-name: ${{ inputs.config }}
    secrets: inherit