name: 'Nattlig restart av testmiljÃ¸'
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  restart-testenvs:
    name: 'Restart test-envs'
    uses: navikt/sosialhjelp-ci/.github/workflows/nightly_restart.yml@master
    secrets: inherit
