name: 'Restart test-milj√∏ (mock og dev-fss)'
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  restart-testenvs:
    name: 'Restart test-envs'
    uses: navikt/sosialhjelp-ci/.github/workflows/restart_test-envs.yml@master
    secrets: inherit
