name: Deploy to Prod-gcp
run-name: Deploy '${{ github.ref_name }}' to 'prog-gcp'
on:
  workflow_dispatch:

jobs:
  deploy-to-prod-gcp:
    name: 'Deploy to prod-gcp'
    permissions:
      id-token: write
      contents: write
    uses: navikt/sosialhjelp-ci/.github/workflows/deploy_app.yml@v7
    with:
      cluster-name: prod-gcp
      resource-name: prod-gcp
      resource-folder: prod
    secrets: inherit
